apiVersion: skaffold/v1beta13
kind: Config
build:
  local: {}
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:{{.IMAGE_TAG}}"
  artifacts:
    - image: dictybase/dictyaccess
      docker:
        dockerfile: docker/staging/Dockerfile
